# services:
#   postfix:
#     build: .
#     container_name: postfix
#     restart: unless-stopped
#     environment:
#       - SMTP_USER=user:password
#       - MAIL_DOMAIN=localhost
#     ports:
#       - "25:25"
#       - "587:587"
#     volumes:
#       - ./certs:/etc/ssl/certs
#       - ./private:/etc/ssl/private
#       - ./postfix/main.cf:/etc/postfix/main.cf
#       - ./postfix/master.cf:/etc/postfix/master.cf
#       - ./dovecot/dovecot.conf:/etc/dovecot/dovecot.conf  # Add this line
#     networks:
#       - mailnet

# networks:
#   mailnet:
#     driver: bridge
services:
  postfix:
    build: .
    container_name: postfix
    restart: unless-stopped
    ports:
      - "25:25"
      - "587:587"
    volumes:
      - ./certs:/etc/ssl/certs:ro
      - ./private:/etc/ssl/private:ro
      - ./postfix/main.cf:/etc/postfix/main.cf
      - ./postfix/master.cf:/etc/postfix/master.cf
      - ./dovecot/dovecot.conf:/etc/dovecot/dovecot.conf
    networks:
      - mailnet

networks:
  mailnet:
    driver: bridge