# Logging to stdout
log_path = /dev/stdout
info_log_path = /dev/stdout
debug_log_path = /dev/stdout

ssl = no
auth_mechanisms = plain login

# Static password for testing
passdb {
  driver = static
  args = password=password
}

userdb {
  driver = static
  args = uid=postfix gid=postfix home=/var/mail/%u
}

# Create the socket inside Postfix's spool directory
service auth {
  unix_listener /var/spool/postfix/private/auth {
    mode = 0660
    user = postfix
    group = postfix
  }
}